### ISSUE TITLE
What's the difference between this and smartparens

### ISSUE THREAD

**Issue by wyuenho** [jtkDvlp/web-mode-edit-element#4]
Hi! Thank you for making this library available! I wanted to try this out, but I was wondering what are the differences between this and [smartparens](https://github.com/Fuco1/smartparens) web-mode support?

**Comment by jtkDvlp** [comment]
Hi wyuenho,

sorry for such late response. I did not get an notification for that or missed it.

I did not use nor know smartparens before, maybe my package offers some more html specialized navigation and functionality. I did not find a docu of the web-mode part, so I have no direct comparison.

Maybe you checked it out in the meanwhile and can share with us?
