### ISSUE TITLE
next-sibling, if not go to the parent

### ISSUE THREAD

**Issue by fniessen** [jtkDvlp/web-mode-edit-element#5]
Just found this package randomly, and looks very interesting for daily usage.

However, one missing shortcut (for me, at least) would be "go to next sibling", but when at end of the list "go to the parent".

Would you add such a one?  Thanks!

**Comment by jtkDvlp** [comment]
Hi fniessen,

thank you for your issue. Sry for late response.

To "go to next sibling" you can the web-mode function "web-mode-element-sibling-next". The behavior to "go to the parent" at the end of the list is special of courese. I can write such function. Which key-binding would you suggest?

**Comment by fniessen** [comment]
Thanks in advance!

No real idea for the key binding. I would personally bind it to M-up/down, more or less like in IntelliJ IDEA.

**Comment by jtkDvlp** [comment]
Please try pre-release v.2.2. Key-Binding for the new function is "C-M-down".
